### ISSUE TITLE
Poor performance with long lists

### ISSUE THREAD

**Issue by ogdenwebb** [DogLooksGood/parinfer-mode#59]
Huh, finally I got it. Well, my Emacs package contains ~500 LOC list with face specs [here](https://github.com/ogdenwebb/emacs-kaolin-themes/blob/340c9f173cb4098da9df3ccf837acf746e04c42f/kaolin-themes-lib.el#L560), but when I try to put something [at the end of file](https://github.com/ogdenwebb/emacs-kaolin-themes/blob/340c9f173cb4098da9df3ccf837acf746e04c42f/kaolin-themes-lib.el#L1154) parinfer causes 1-2 seconds delay before I can see anything in the current buffer. Works fine if I have list with 100 or maybe 200 LOC.

Tested with completely clear Emacs configuration(only parinfer installed) and also with the two other packages(doom-themes and gruvbox) similar to mine.

GNU Emacs 25.3.1 (x86_64-pc-linux-gnu, GTK+ Version 3.22.19) of 2018-02-12
Parinfer installed from MELPA, parinfer-20180214.1040. Default config for use-package taken from README.md.

**Comment by DogLooksGood** [comment]
Hi, yes, parinfer-mode has bad performance.

The solution is: now, a new version rewriting is under branch [smart](https://github.com/DogLooksGood/parinfer-mode/tree/smart) , file [parinfer-smart.el](https://github.com/DogLooksGood/parinfer-mode/blob/smart/parinfer-smart.el).

New version ships smart mode and have much better performance, also some wired bugs will be fixed hopefully. This new version, on my MBP 2015, takes about 30ms ~ 70ms when process 2900 LOC(current version cost 1000ms). It's about 15x faster than the current version.

At this moment, if you want to try on new version, try this:
 https://github.com/DogLooksGood/parinfer-mode-demo.

Close issue since there's no plan to improve the performance of current version.
